services:
  mssql:
    build:
      context: .
      dockerfile_inline: |
        # Please note that this is not a Microsoft SQL Server image, this is a custom image that installs the necessary tools to connect to a Microsoft SQL Server
        FROM alpine:latest
        
        # Update and upgrade
        RUN apk update
        RUN apk upgrade

        # Install dependencies
        RUN apk add curl gnupg

        # Download the desired package(s)
        RUN curl -O https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/msodbcsql18_18.3.3.1-1_amd64.apk
        RUN curl -O https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/mssql-tools18_18.3.1.1-1_amd64.apk

        #(Optional) Verify signature, if 'gpg' is missing install it using 'apk add gnupg':
        RUN curl -O https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/msodbcsql18_18.3.3.1-1_amd64.sig
        RUN curl -O https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/mssql-tools18_18.3.1.1-1_amd64.sig

        RUN curl https://packages.microsoft.com/keys/microsoft.asc  | gpg --import -
        RUN gpg --verify msodbcsql18_18.3.3.1-1_amd64.sig msodbcsql18_18.3.3.1-1_amd64.apk
        RUN gpg --verify mssql-tools18_18.3.1.1-1_amd64.sig mssql-tools18_18.3.1.1-1_amd64.apk

        # Install the package(s)
        RUN apk add --allow-untrusted msodbcsql18_18.3.3.1-1_amd64.apk
        RUN apk add --allow-untrusted mssql-tools18_18.3.1.1-1_amd64.apk