# TODO: Link volume to persist data
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
    #  - postgres:/var/lib/postgresql/data # Verify correct path
    ports:
      - 5432:5432
volumes:
  postgres: